### ISSUE TITLE
plugin fails to load on paper server, loads fine on spigot

### ISSUE THREAD

**Issue by leefy-greens** [imDMK/DoubleJump#44]
**Describe the bug**
plugin won't load on paper server

**How do you trigger it?**
start the paper server witht the DoubleJump .jar in the plugins folder

**Console log**
[12:38:19 INFO]: [DoubleJump] Enabling DoubleJump v2.1.4
[12:38:19 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftMetaItem
[12:38:19 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[12:38:19 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[12:38:19 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[12:38:19 WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[12:38:19 WARN]: 	at java.base/java.lang.Class.forName(Class.java:529)
[12:38:19 WARN]: 	at java.base/java.lang.Class.forName(Class.java:508)
[12:38:19 WARN]: 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[12:38:19 WARN]: 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.lib.dev.triumphteam.gui.components.util.VersionHelper.craftClass(VersionHelper.java:143)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.lib.dev.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:77)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.jump.item.JumpItemSettings.<init>(JumpItemSettings.java:32)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.jump.JumpSettings.<init>(JumpSettings.java:47)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.configuration.implementation.PluginConfiguration.<init>(PluginConfiguration.java:36)
[12:38:19 WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[12:38:19 WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[12:38:19 WARN]: 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:132)
[12:38:19 WARN]: 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:259)
[12:38:19 WARN]: 	at java.base/java.lang.Class.newInstance(Class.java:755)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.lib.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:22)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.configuration.ConfigurationFactory.create(ConfigurationFactory.java:33)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.DoubleJump.<init>(DoubleJump.java:103)
[12:38:19 WARN]: 	at DoubleJump v2.1.4.jar//com.github.imdmk.doublejump.DoubleJumpPlugin.onEnable(DoubleJumpPlugin.java:11)
[12:38:19 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[12:38:19 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[12:38:19 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[12:38:19 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[12:38:19 WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604)
[12:38:19 WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553)
[12:38:19 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[12:38:19 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[12:38:19 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323)
[12:38:19 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
[12:38:19 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[12:38:19 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[12:38:19 ERROR]: Error occurred while enabling DoubleJump v2.1.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.jump.item.JumpItemSettings.<init>(JumpItemSettings.java:32) ~[DoubleJump v2.1.4.jar:?]
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.jump.JumpSettings.<init>(JumpSettings.java:47) ~[DoubleJump v2.1.4.jar:?]
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.configuration.implementation.PluginConfiguration.<init>(PluginConfiguration.java:36) ~[DoubleJump v2.1.4.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:132) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:259) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:755) ~[?:?]
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.lib.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:22) ~[DoubleJump v2.1.4.jar:?]
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.configuration.ConfigurationFactory.create(ConfigurationFactory.java:33) ~[DoubleJump v2.1.4.jar:?]
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.DoubleJump.<init>(DoubleJump.java:103) ~[DoubleJump v2.1.4.jar:?]
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.DoubleJumpPlugin.onEnable(DoubleJumpPlugin.java:11) ~[DoubleJump v2.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: com.github.imdmk.doublejump.lib.dev.triumphteam.gui.components.exception.GuiException: Could not retrieve displayName nor lore field for ItemBuilder.
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.lib.dev.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:86) ~[DoubleJump v2.1.4.jar:?]
	... 24 more
[12:38:19 INFO]: [DoubleJump] Disabling DoubleJump v2.1.4
[12:38:19 ERROR]: Error occurred while disabling DoubleJump v2.1.4
java.lang.NullPointerException: Cannot invoke "com.github.imdmk.doublejump.DoubleJump.disable()" because "this.doubleJump" is null
	at DoubleJump v2.1.4.jar/com.github.imdmk.doublejump.DoubleJumpPlugin.onDisable(DoubleJumpPlugin.java:16) ~[DoubleJump v2.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Server version**
Use **/ver** command and paste here.
This server is running Paper version 1.20.6-137-master@bd5867a  (Implementing API version 1.20.6-R0.1-SNAPSHOT)

**Plugin version**
Use **/ver DoubleJump** command and paste here.
v2.1.4

**Plugin configuration**
no config yet, plugin won't load

**Screenshots or Video**
n/a

**Additional context**
works perfectly fine on spigot of the same version, fails to load on paper.

**Comment by leefy-greens** [comment]
wrong description, will try again.
