### ISSUE TITLE
Issue with new plugin version.

### ISSUE THREAD

**Issue by shneckle28** [imDMK/DoubleJump#50]
**Describe the bug**
Issue when the plugin is trying to load.

**How do you trigger it?**
restarting the server

**Console log**
[17:19:21 ERROR]: Error occurred while enabling DoubleJump v2.1.5 (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.Particle does not have member field 'org.bukkit.Particle BUBBLE'
        at com.github.imdmk.doublejump.jump.particle.JumpParticleSettings.<init>(JumpParticleSettings.java:15) ~[DoubleJump.v2.1.5.jar:?]
        at com.github.imdmk.doublejump.jump.JumpSettings.<init>(JumpSettings.java:41) ~[DoubleJump.v2.1.5.jar:?]
        at com.github.imdmk.doublejump.configuration.implementation.PluginConfiguration.<init>(PluginConfiguration.java:36) ~[DoubleJump.v2.1.5.jar:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
        at java.lang.Class.newInstance(Class.java:725) ~[?:?]
        at com.github.imdmk.doublejump.lib.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:22) ~[DoubleJump.v2.1.5.jar:?]
        at com.github.imdmk.doublejump.configuration.ConfigurationFactory.create(ConfigurationFactory.java:33) ~[DoubleJump.v2.1.5.jar:?]
        at com.github.imdmk.doublejump.configuration.ConfigurationService.create(ConfigurationService.java:14) ~[DoubleJump.v2.1.5.jar:?]
        at com.github.imdmk.doublejump.DoubleJump.<init>(DoubleJump.java:105) ~[DoubleJump.v2.1.5.jar:?]
        at com.github.imdmk.doublejump.DoubleJumpPlugin.onEnable(DoubleJumpPlugin.java:11) ~[DoubleJump.v2.1.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]

**Server version**
1.20.4

**Plugin version**
2.1.5

**Plugin configuration**
Paste here your plugin configuration.

**Screenshots or Video**
If applicable, add screenshots or link to video to help explain your problem.

**Additional context**

**Comment by imDMK** [comment]
Hi, thanks for the issue.

Error log shows that a particle called BUBBLE does not exist. It may exist in version 1.20.4, but the plugin uses the latest server library 1.21, which does not contain this particle.

**Comment by shneckle28** [comment]
Is there anyway you can send me a copy of the old update? I no longer have it.

**Comment by shneckle28** [comment]
nvm I got it, Thanks.

**Comment by imDMK** [comment]
> Is there anyway you can send me a copy of the old update? I no longer have it.

 I think you should check if this particle has been replaced by another name. I doubt Mojang simply removed this particle.  If necessary, I will send you a file with a different API version, but not all functions may work correctly. 
Regards.

**Comment by imDMK** [comment]
> nvm I got it, Thanks.

Great! Have a nice day/night.
