### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by WaterChick** [imDMK/DoubleJump#52]
**Describe the bug**
I got a NoSuchFieldError BUBBLE while starting the server

**How do you trigger it?**
I just downloaded the plugin and put it in plugins folder

**Console log**
[20:01:35 ERROR]: Error occurred while enabling DoubleJump v2.1.5 (Is it up to date?)
java.lang.NoSuchFieldError: BUBBLE
        at com.github.imdmk.doublejump.jump.particle.JumpParticleSettings.<init>(JumpParticleSettings.java:15) ~[DoubleJump v2.1.5.jar:?]
        at com.github.imdmk.doublejump.jump.JumpSettings.<init>(JumpSettings.java:41) ~[DoubleJump v2.1.5.jar:?]
        at com.github.imdmk.doublejump.configuration.implementation.PluginConfiguration.<init>(PluginConfiguration.java:36) ~[DoubleJump v2.1.5.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at com.github.imdmk.doublejump.lib.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:22) ~[DoubleJump v2.1.5.jar:?]
        at com.github.imdmk.doublejump.configuration.ConfigurationFactory.create(ConfigurationFactory.java:33) ~[DoubleJump v2.1.5.jar:?]
        at com.github.imdmk.doublejump.configuration.ConfigurationService.create(ConfigurationService.java:14) ~[DoubleJump v2.1.5.jar:?]
        at com.github.imdmk.doublejump.DoubleJump.<init>(DoubleJump.java:105) ~[DoubleJump v2.1.5.jar:?]
        at com.github.imdmk.doublejump.DoubleJumpPlugin.onEnable(DoubleJumpPlugin.java:11) ~[DoubleJump v2.1.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Server version**
This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)

**Plugin version**
DoubleJump version 2.1.5
Efficient double jump plugin with many features and configuration possibilities
Website: https://github.com/imDMK/DoubleJump
Author: DMK

**Plugin configuration**
It did not create a config

**Comment by imDMK** [comment]
Hi, thanks for the issue.

Error log shows that a particle called BUBBLE does not exist. It may exist in version 1.20.4, but the plugin uses the latest server library 1.21, which does not contain this particle.

This is the same issue as #50.
