### ISSUE TITLE
Error occurred while enabling DoubleJump v2.0.2

### ISSUE THREAD

**Issue by DrBlender** [imDMK/DoubleJump#8]
After putting the plugin in plugin folder i got this error after starting the server

[01:52:33] [Server thread/ERROR]: Error occurred while enabling DoubleJump v2.0.2 (Is it up to date?)
com.eternalcode.gitcheck.git.GitException: The response code is not 200
	at com.eternalcode.gitcheck.github.GitHubReleaseProvider.requestLastRelease(GitHubReleaseProvider.java:58) ~[doublejump-core-2.0.2.jar:?]
	at com.eternalcode.gitcheck.github.GitHubReleaseProvider.getLatestRelease(GitHubReleaseProvider.java:26) ~[doublejump-core-2.0.2.jar:?]
	at com.eternalcode.gitcheck.GitCheck.getLatestRelease(GitCheck.java:49) ~[doublejump-core-2.0.2.jar:?]
	at com.eternalcode.gitcheck.GitCheck.checkRelease(GitCheck.java:66) ~[doublejump-core-2.0.2.jar:?]
	at me.dmk.doublejump.DoubleJump.checkForUpdate(DoubleJump.java:152) ~[doublejump-core-2.0.2.jar:?]
	at me.dmk.doublejump.DoubleJump.<init>(DoubleJump.java:114) ~[doublejump-core-2.0.2.jar:?]
	at me.dmk.doublejump.DoubleJumpPlugin.onEnable(DoubleJumpPlugin.java:11) ~[doublejump-core-2.0.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-47]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-47]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:52:33] [Server thread/INFO]: [DoubleJump] Disabling DoubleJump v2.0.2
[01:52:33] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling DoubleJump v2.0.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.dmk.doublejump.DoubleJump.disable()" because "this.doubleJump" is null
	at me.dmk.doublejump.DoubleJumpPlugin.onDisable(DoubleJumpPlugin.java:16) ~[doublejump-core-2.0.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-47]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-47]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-47]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by imDMK** [comment]
Thank you for reporting.
Is the problem still present? If it still does, try disabling the checkForUpdate option in the configuration.

**Comment by imDMK** [comment]
I'm closing this issue because it's not the plugin's fault. 
I have released a patch that will make the plugin work even if there is a problem with checking for updates.
